version: '3'
services:
  flexapi:
    container_name: flexapi
    image: flexapi
    restart: always
    build: 
      context: .
      dockerfile: ./Docker/API/Dockerfile 
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/uploads
    
  flexcdn:
    container_name: flexcdn
    image: flexcdn
    restart: always
    build: 
      context: .
      dockerfile: ./Docker/CDN/Dockerfile 
    ports:
      - '3355:3355'
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/uploads
    
  flexclient:
    container_name: flexclient
    image: flexclient
    restart: always
    build: 
      context: .
      dockerfile: ./Docker/CLIENT/Dockerfile
    ports:
      - '3333:3333'
    volumes:
      - ./uploads:/usr/src/uploads

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}
      - APP_MONGO_DB=${APP_MONGO_DB}
    volumes:
      - ./mongodb/data:/data/db
      - "./scripts/:/docker-entrypoint-initdb.d/"
