version: '2'
services:
  lazyDrive:
    container_name: lazyDrive
    image: lazyDrive
    restart: always
    build: .
    ports:
      - '80:3333'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
