version: '2'
services:
  flexoriginals:
    container_name: flexoriginals
    image: flexoriginals
    restart: always
    build: .
    ports:
      - '80:3333'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
