version: '2'
services:
  lazydrive:
    container_name: lazydrive
    restart: always
    build: .
    ports:
      - '3344:3344'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
