version: "3"
services:
  flexclient:
    container_name: flexclient
    image: flexclient
    restart: always
    build:
      context: .
      dockerfile: ./Docker/CLIENT/Dockerfile
    ports:
      - "${APP_CLIENT_PORT}:${APP_CLIENT_PORT}"
    links:
      - flexapi
    volumes:
      - ./uploads:/usr/src/uploads

  flexapi:
    container_name: flexapi
    image: flexapi
    restart: always
    build:
      context: .
      dockerfile: ./Docker/API/Dockerfile
    ports:
      - "${APP_API_PORT}:${APP_API_PORT}"
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/uploads

  flexcdn:
    container_name: flexcdn
    image: flexcdn
    restart: always
    build:
      context: .
      dockerfile: ./Docker/CDN/Dockerfile
    ports:
      - "${APP_CDN_PORT}:${APP_CDN_PORT}"
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/uploads

  mongo:
    container_name: mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./scripts/mongo/mongo-user-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-user-entrypoint.sh
      # - ./scripts/mongo/user/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      # - ./mongodb/data:/data/db
      # - ./mongodb/mongodb_config:/data/configdb
