version: '3'
services:

  flexclient:
    container_name: flexclient
    image: flexclient
    restart: always
    build: 
      context: .
      dockerfile: ./Docker/CLIENT/Dockerfile
    ports:
      - '3333:3333'
    links:
      - flexapi
    volumes:
      - ./uploads:/usr/src/uploads

  flexapi:
    container_name: flexapi
    image: flexapi
    restart: always
    build: 
      context: .
      dockerfile: ./Docker/API/Dockerfile 
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/uploads
    
  flexcdn:
    container_name: flexcdn
    image: flexcdn
    restart: always
    build: 
      context: .
      dockerfile: ./Docker/CDN/Dockerfile 
    ports:
      - '3355:3355'
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/uploads

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
